name: maydon_go
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  lottie: ^3.2.0
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  carousel_slider: ^5.0.0
  flutter_multi_formatter: ^2.13.0
  go_router: ^14.6.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar: ^6.2.1
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.4
  logger: ^2.5.0
  permission_handler: ^11.3.1
  flutter_bloc: ^9.0.0
  country_flags: ^3.2.0

  cached_network_image: ^3.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
flutter:

  generate: true
  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/
    - assets/icons/



  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Extrabold.ttf
          weight: 800

